/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Simulation.DiscreteSimulation;

import Simulation.ConstraintDialog;
import groovy.lang.Binding;
import groovy.lang.GroovyShell;
import groovy.lang.Script;
import java.awt.Window;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import modular_stream.Kernel;
import modular_stream.StreamNode;
import modular_stream.TimerDialog;

/**
 *
 * @author Amir72c
 */
public class DiscreteOutput extends Kernel {

    Binding main_binding;
    GroovyShell main_shell;
    Script compiledConstriant;
    TimerDialog myrootTimer;
    String constraintExp="";
    ConstraintDialog constraintDialog;

    /**
     * Creates new form DiscreteOutput
     */
    public DiscreteOutput(final StreamNode parent, double Inputs[]) {
        initComponents();
        main_binding = new Binding();
        main_shell = new GroovyShell(main_binding);
        main_binding.setVariable("Inputs", Inputs);
        myrootTimer = parent.mySteamPanelParent.root_timer;
        //parent.mySteamPanelParent.root_timer
        Window parentWindow = SwingUtilities.windowForComponent(this);
        
        constraintDialog=new ConstraintDialog((JFrame) parentWindow,true,parent);//************
    }

    @Override
    public void parseKernel() {
        constraintExp=constraintDialog.Const.getText();
        String temp_string = "import java.math.*;";
        if (constraintExp.length() > 0) {
            temp_string = temp_string + "def evalConstraint" + "(){final_value=(" + constraintExp + ");return final_value;};";
        } else {
            temp_string = temp_string + "def evalConstraint" + "(){final_value=true;return final_value;};";
        }
        compiledConstriant = main_shell.parse(temp_string);

    }

    @Override
    public double runKernel() {
        Output[0] = (int) jSpinner1.getValue();
        boolean tempConstraint = Boolean.parseBoolean(compiledConstriant.invokeMethod("evalConstraint", null).toString());
        if (tempConstraint) {
            return Output[0];
        } else {
            return 0;
        }

    }
    boolean isEditted = false;
    
    @Override
    public void writeExternal(ObjectOutput out) throws IOException {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Constraints:");

        jLabel2.setText("Output:");

        jButton1.setText("Define constraints");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        constraintDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
